Repository Sage/carbon-factory, pull requests merged in 2018-07, with the labels that each got.

#201 Safe CSS processor options
  CHANGELOG.md
  package-lock.json
  package.json
  webpack.config.js
Labels: Passed Review

#156 Added spyOn example
  docs/help-with-jest.md
Labels: Passed Review, enhancement

#202 removed gulp support; v5.0.0
  .babelrc
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/carbon-app.zip
  docs/command-line-interface.md
  docs/handlers.md
  docs/standalone-build.md
  docs/standard-build.md
  gulpfile.js
  jest.conf.json
  package-lock.json
  package.json
  src/carbon-app.js
  src/carbon-component.js
  src/carbon-standalone.js
  src/cli.js
  src/gulp/__spec_helper__/index.js
  src/gulp/build.js
  src/gulp/karma.conf.js
  src/gulp/lint.js
  src/gulp/spec.js
  src/gulp/utils/fs-patch.js
  src/prep-tasks/create-app-structure.js
  src/prep-tasks/create-standalone-structure.js
  src/tpl/babelrc.txt
  src/tpl/component-package.js
  src/tpl/component.js
  src/tpl/component.spec.js
  src/tpl/eslintrc.txt
  src/tpl/gitignore.txt
  src/tpl/gulpfile-standalone.js
  src/tpl/gulpfile.js
  src/tpl/index.html
  src/tpl/main-standalone.js
  src/tpl/main.js
  src/tpl/package.txt
  src/utils/clone.js
  src/utils/createDirectory.js
Labels: Passed QA, Passed Review

#203 Updated Dependencies for v5
  .eslintrc
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Passed Review

#205 added --stats
  CHANGELOG.md
  docs/webpack.md
  package-lock.json
  package.json
  webpack.config.js
Labels: Passed Review
