Repository Sage/carbon-factory, pull requests merged in 2018-10, with the labels that each got.

#210 Remove parcelify loader
  CHANGELOG.md
  docs/webpack.md
  package-lock.json
  package.json
  webpack.config.js
Labels: Passed Review, Requires QA

#211 sets up babel-polyfill
  .babelrc
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Passed QA, Passed Review

#212 jsx support - v6.1.1
  CHANGELOG.md
  package-lock.json
  package.json
  webpack.config.js
Labels: Passed Review
