Repository Sage/carbon-factory, pull requests merged in 2019-06, with the labels that each got.

#227 Bumps jest and webpack-css dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Passed Review, dependencies

#228 Drops and Locks webpack-dev-server
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Pending Review, dependencies

#229 FE-1646 core-js 3
  CHANGELOG.md
  babel.config.js
  package-lock.json
  package.json
  webpack.config.js
Labels: Passed Review, Squad Front End Eng
